project_name: steadybit-extension-prometheus
version: 2
before:
  hooks:
    - go mod download
    - make licenses-report

release:
  prerelease: "false"

git:
  ignore_tags:
    - steadybit-extension-prometheus-*

builds:
  - binary: extension-prometheus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -cover={{ if index .Env "BUILD_WITH_COVERAGE"  }}{{ .Env.BUILD_WITH_COVERAGE }}{{ else }}false{{ end }}
      - -covermode=atomic
    ldflags:
      - -s -w
      - -X github.com/steadybit/extension-kit/extbuild.ExtensionName={{.ProjectName}}
      - -X github.com/steadybit/extension-kit/extbuild.Version={{.Version}}
      - -X github.com/steadybit/extension-kit/extbuild.Revision={{.Commit}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-{{ .Timestamp }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - package_name: "steadybit-extension-prometheus"
    file_name_template: "{{ .ConventionalFileName }}"
    formats:
      - deb
      - rpm
    maintainer: "Johannes Edmeier <johannes.edmeier@steadybit.com>"
    description: |
      Steadybit Extension Prometheus
    vendor: "steadybit GmbH"
    homepage: "https://steadybit.com"
    license: "Steadybit license"
    builds:
      - steadybit-extension-prometheus
    bindir: /opt/steadybit/extension-prometheus
    contents:
      - src: ./linuxpkg/systemd
        dst: /usr/lib/systemd/system
      - src: ./linuxpkg/init.d
        dst: /etc/init.d
      - src: ./linuxpkg/config
        dst: /etc
        type: config
      - src: ./licenses
        dst: /opt/steadybit/extension-prometheus/licenses
    scripts:
      preinstall: ./linuxpkg/scripts/preinstall.sh
      postinstall: ./linuxpkg/scripts/postinstall.sh
      preremove: ./linuxpkg/scripts/preremove.sh
      postremove: ./linuxpkg/scripts/postremove.sh

    rpm:
      signature:
        key_file: ./gpg.key
    deb:
      signature:
        key_file: ./gpg.key
